import = [
  "~/.config/alacritty/themes/themes/catppuccin-macchiato.toml"
]

[env]
TERM = "xterm-256color"

[window]
blur = true
opacity = 0.85
startup_mode = "Maximized"
dynamic_padding = true
decorations = "None"

[font]
normal = { family = "MesloLGMDZ Nerd Font", style = "Regular" }
size = 9.1
builtin_box_drawing = true

[scrolling]
history = 10000
multiplier = 3

[mouse]
hide_when_typing = true

[shell]
program = "/bin/bash"
args = ["-c", '''
if [ -z "$TMUX" ]; then
  exec tmux
else
  exec bash
fi
''']
