[window]
title = "Alacritty"
dynamic_title = true
decorations = "full"
startup_mode = "Fullscreen"
blur = true
opacity = 0.98

[font]
normal = { family = "Source Code Pro", style = "Regular" }
size = 12.0
builtin_box_drawing = true

[scrolling]
history = 10000
multiplier = 3

[mouse]
hide_when_typing = true

[shell]
program = "/bin/bash"
args = ["-c", '''
if [ -z "$TMUX" ]; then
  exec tmux
else
  exec bash
fi
''']
